
dataset_version : low_br

ss_grid : [5000, 50000, 100000, 200000]
em_grid : [50, 70, 90]
type_grid : [dedupe, record_linkage]
iteration_grid : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

blocked_proportion_grid: [50, 90]
sample_size_grid: [1500, 15000, 150000, 300000]
budget_grid: [20, 40, 80, 200, 500, 1000]

default_value : 0
